package org.hr24.almel.ResumeDesigner.utils;

/**
 * Created by Alexey on 02.08.16.
 */
public interface ConstantManager {


    String USER_NAME_KEY = "USER_0_KEY";
    String USER_NICK_KEY = "USER_1_KEY";
    String USER_PHONE_KEY= "USER_2_KEY";
    String USER_MAIL_KEY= "USER_3_KEY";
    String USER_BIO_KEY= "USER_4_KEY";
    String USER_SKILLS_KEY = "USER_5_KEY";
    String USER_LANGUAGES_KEY = "USER_6_KEY";
    String USER_HOBBY_KEY = "USER_7_KEY";
    String USER_JOB_PERIOD_KEY = "USER_8_KEY";
    String USER_COMPANY_TITLE_KEY = "USER_9_KEY";
    String USER_JOB_TITLE_KEY = "USER_10_KEY";
    String USER_JOB_DUTY_KEY = "USER_11_KEY";
    String USER_STUDY_TITLE_KEY = "USER_12_KEY";
    String USER_STUDY_DESCRIPTION_KEY = "USER_13_KEY";
    String USER_RATING_KEY = "USER_14_KEY";
    String USER_ACHIEVEMENTS_KEY = "USER_15_KEY";

    String USER_STUDY_2_TITLE_KEY = "USER_16_KEY";
    String USER_STUDY_2_DESCRIPTION_KEY = "USER_17_KEY";
    String USER_RATING_2_KEY = "USER_18_KEY";

    String USER_JOB_2_PERIOD_KEY = "USER_19_KEY";
    String USER_COMPANY_2_TITLE_KEY = "USER_20_KEY";
    String USER_JOB_2_TITLE_KEY = "USER_21_KEY";
    String USER_JOB_2_DUTY_KEY = "USER_22_KEY";

    String USER_JOB_3_PERIOD_KEY = "USER_23_KEY";
    String USER_COMPANY_3_TITLE_KEY = "USER_24_KEY";
    String USER_JOB_3_TITLE_KEY = "USER_25_KEY";
    String USER_JOB_3_DUTY_KEY = "USER_26_KEY";



    String JOB_COUNT_KEY = "JOB_COUNT_KEY";
    String STUDY_COUNT_KEY = "STUDY_COUNT_KEY";

    String PHOTO_SET_STATUS_KEY = "PHOTO_SET_STATUS_KEY";

    String AUTHORIZATION_STATUS_KEY = "AUTHORIZATION_STATUS_KEY";
    String POST_STATUS_KEY = "POST_STATUS_KEY";

    String PREMIUM_STATUS_KEY = "PREMIUM_STATUS_KEY";

    String USER_PHOTO_KEY="USER_PHOTO_KEY";

    int REQUEST_GALLERY_PICTURE=88;
    int REQUEST_CAMERA_PICTURE = 99;

    int PERMISSION_REQUEST_SETTINGS_CODE = 101;
    int CAMERA_REQUEST_PERMISSION_CODE = 102;


    String FIRST_WORK_STATUS_KEY = "FIRST_WORK_STATUS_KEY";
    String PREMIUM_ALREADY_OWNED_STATUS_KEY = "PREMIUM_ALREADY_OWNED_STATUS_KEY";
}
